ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: cluster-issuer
  hosts:
    - host: uptime-demo.94.co.ucll.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: uptime-demo-kuma-tls
      hosts:
        - uptime-demo.94.co.ucll.cloud
